### ISSUE TITLE
Repeated matches showing in parser_references

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/reference-parser#26]
In the parser_references RDS data there should really only be unique publications-policy documents matches (apart from a few possible cases where a policy document has multiple references sections and therefore the reference is repeated).
However, we find quite a few repeated matches, and some which have different date stamps (which I don't think should ever happen).

A screenshot of one particular case is attached. Here publication 'pub.1000468642' was found 20 times in document '1786430', 5 times for each of the 4 times the webpage was scraped. 

![screenshot 2019-01-08 at 11 53 14](https://user-images.githubusercontent.com/15956065/50829319-04bd6f80-133c-11e9-8b26-40e4ddca2102.png)

Hence there are 2 possible issues here that should be investigated:
- why are some matches repeated in the database?
- why are matches repeated in multiple scrapes of the website (if they were already matched in the past then later matches shouldn't be included)

**Comment by SamDepardieu** [comment]
Hey @lizgzil !
I see what's going on here. We're filtering the references but not the matches, leading to these duplications. I'm adding a postit on the board. Will fix this week 👍
