### ISSUE TITLE
pep8 and pyflakes

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/reference-parser#32]
Since as part of the PR we need to check pep8 and pyflakes, should we add these to the requirements? I am happy to submit this PR if this is a good idea? @hblanks @SamDepardieu

**Comment by hblanks** [comment]
I tend to view the requirements file as what you need to run or test the product, so, no, probably not.

We should update the README to say that your dev env should have these packages present though. And, if they're ever automated into tests, then perhaps we'd have a separate test_requirements.txt for such things.

**Comment by hblanks** [comment]
...on second thought, CONTRIBUTING.md states this fairly clearly already, so, I think we leave it alone.

If we do want to automate though, don't hesitate to add a PR updating the Makefile, so that the virtualenv also includes these packages.
